### ISSUE TITLE
Support for OSX?

### ISSUE THREAD

**Issue by thedon-chris** [Intel-EPID-SDK/epid-sdk#2]
Does the SDK support OSX? 

The documentation mentions only windows/linux.

**Comment by tletnes** [comment]
The SDK is designed to be usable on a wide variety of platforms. We test on Windows and Linux , but we expect it to work on most platforms. There is very little, if any, OS specific code in the core SDK (excluding unit tests and samples) and we have tried to minimize compiler specific code as well.
