### ISSUE TITLE
What does "tiny" refer to?

### ISSUE THREAD

**Issue by eozturk1** [Intel-EPID-SDK/epid-sdk#7]
What does tiny refer to for implementations under `member/tiny`? Is this an optimized implementation in terms of space usage or computation cost?

**Comment by jdominik-intel** [comment]
Hi the term tiny refers to implementation optimized in terms of space usage.

**Comment by eozturk1** [comment]
Is there a performance-optimized version of the `tiny` library available?

**Comment by jdominik-intel** [comment]
No that's the only `tiny` implementation.
