### ISSUE TITLE
Possible performance improvements

### ISSUE THREAD

**Issue by eozturk1** [Intel-EPID-SDK/epid-sdk#8]
We are trying to improve the performance of EPID and and were wondering what are some places that this is possible, e.g., compilation options, replacing IPP-Crypto with an optimized version?

**Comment by jdominik-intel** [comment]
Hi,

the easiest way to would be to use optimized IPP-Crypto:
https://software.intel.com/content/www/us/en/develop/tools/integrated-performance-primitives.html
