### ISSUE TITLE
Tool for generating revocation lists?

### ISSUE THREAD

**Issue by eozturk1** [Intel-EPID-SDK/epid-sdk#9]
We are trying to measure the performance of EPID regarding different revocation list sizes and we are using available revocation lists under `example/data`. Is there a tool available for generating revocations lists with varying sizes?

If there is not, are the formats of the revocation lists available?

**Comment by mpkolasi** [comment]
Unfortunately such a tool is not available.
EPID defines three Roles: Verifier, Member and Issuer. Issuer is responsible for managing EPID group membership, which includes revocation list creation. Currently only Verifier and Member Roles are available as an Open Source solution.
